### ISSUE TITLE
Can't compile with opencv 4.1.1

### ISSUE THREAD

**Issue by rversteegen** [azagaya/laigter#36]
Firstly, on Unix qmake produces a warning (which breaks `qmake && make`):
> WARNING: Failure to find: gui/Widgets/slider.h

This is fixed by replacing Widgets with widgets in laigter.pro.

But after that I still can't compile:
```
src/imageprocessor.cpp: In member function ‘int ImageProcessor::loadImage(QString, QImage)’:
src/imageprocessor.cpp:175:30: error: reference to ‘COLOR_GRAY2RGBA’ is ambiguous
  175 |       cvtColor(m_img, m_img, COLOR_GRAY2RGBA);
      |                              ^~~~~~~~~~~~~~~
In file included from /usr/include/opencv4/opencv2/opencv.hpp:74,
                 from src/imageprocessor.h:36,
                 from src/imageprocessor.cpp:20:
/usr/include/opencv4/opencv2/imgproc.hpp:545:5: note: candidates are: ‘cv::ColorConversionCodes cv::COLOR_GRAY2RGBA’
  545 |     COLOR_GRAY2RGBA    = COLOR_GRAY2BGRA,
      |     ^~~~~~~~~~~~~~~
<command-line>: note:                 ‘<unnamed enum> COLOR_GRAY2RGBA’
```
(Similar errors follow)

To compile, I had to remove all 5 of the `DEFINES +=` lines from laigter.pro.
Using GCC 9.2.0, qmake 3.1, Qt 5.13.2, opencv 4.1.1, x86_64 linux (Slackware)

**Comment by azagaya** [comment]
Thanks a lot for reporting! 
Those defines were there because I couldn't compile on some OS without them, and it is working on my linux machine. I'll have to check on which platforms i need those defines, so we can add conditionals to only define them on desired systems. Sadly, i don't have a windows machine in this moments, but i'll check it as soon as possible!

**Comment by azagaya** [comment]
Now that i checked properly, i remember those defines where added because an user couldnt compile on Manjaro Linux with opencv 4.0 without them.
I will need to check this further.

**Comment by azagaya** [comment]
I've tested in other systems and it seems to work fine now without the defines. Im removing them in bb004d8 
Will add them again with proper conditionals if someone reports they are needed again.
